# Spring properties
spring:
  application:
    name: quote-service  # Service registers under this name
  freemarker:
    enabled: false           # Ignore Eureka dashboard FreeMarker templates


# HTTP Server
server.port: 2222   # HTTP (Tomcat) port